backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/uploads # Media files will be stored in the repo under static/images/uploads
public_folder: /uploads # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "content" # Used in routes, e.g., /admin/collections/tracks
    label: "Content" # Used in the UI
    extension: "json"
    format: "json"
    editor:
      preview: false

    files:
      - file: "src/data/tracks.json" # The path to the file where our data is stored
        name: tracks
        label: Tracks
        fields: # The fields for each track
            - name: tracks
              widget: list
              fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Sound File", name: "file", widget: "file" }
              - { label: "Cover Image", name: "image", widget: "image" }

      - file: "src/data/info.json"
        name: info
        label: Info
        fields:
          - { label: "Bio", name: "bio", widget: "text" }
          - name: links
            label: Links
            widget: list
            fields: 
              - { label: "Text", name: "text", widget: string }
              - { label: "url", name: "url", widget: string }